global using Centrex.Models;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.VisualBasic;
global using Microsoft.VisualBasic.CompilerServices;

global using MarcaEntity = Centrex.Models.MarcaItemEntity;
global using static Centrex.VariablesGlobales;
global using Centrex.Funciones;

//global using Centrex.Generales;
global using static Centrex.Funciones.DataGridQueryResult;
global using static Centrex.Funciones.LoadDataGridDynamic;
global using static Centrex.Funciones.generales;
global using static Centrex.Funciones.ajustes_stock;
global using static Centrex.Funciones.asocitems;
global using static Centrex.Funciones.bancos;
global using static Centrex.Funciones.cajas;
global using static Centrex.Funciones.cambios;
global using static Centrex.Funciones.ccClientes;
global using static Centrex.Funciones.ccProveedores;
global using static Centrex.Funciones.cheques;
global using static Centrex.Funciones.clientes;
global using static Centrex.Funciones.cobros_retenciones;
global using static Centrex.Funciones.cobros;
global using static Centrex.Funciones.combos_alias;
global using static Centrex.Funciones.combos_ef_extra;
global using static Centrex.Funciones.combos_ef;
global using static Centrex.Funciones.comprobantes_compras;
global using static Centrex.Funciones.comprobantes;
global using static Centrex.Funciones.conceptos_compra;
global using static Centrex.Funciones.condiciones_compra;
global using static Centrex.Funciones.condiciones_venta;
global using static Centrex.Funciones.consultas;
global using static Centrex.Funciones.consultaSIAP;
global using static Centrex.Funciones.consultasSIAP;
global using static Centrex.Funciones.cuentas_bancarias;
global using static Centrex.Funciones.impuestos;
global using static Centrex.Funciones.itemsImpuestos;
global using static Centrex.Funciones.marcasitems;
global using static Centrex.Funciones.mitem;
global using static Centrex.Funciones.ordenesCompras;
global using static Centrex.Funciones.pagos;
global using static Centrex.Funciones.Pedidos;
global using static Centrex.Funciones.perfiles;
global using static Centrex.Funciones.permisos;
global using static Centrex.Funciones.producciones;
global using static Centrex.Funciones.proveedores;
global using static Centrex.Funciones.rutinas;
global using static Centrex.Funciones.stock;
global using static Centrex.Funciones.tipositems;
global using static Centrex.Funciones.transacciones;
global using static Centrex.Funciones.transferencias;
global using static Centrex.Funciones.usuarios;
global using static Centrex.Funciones.ConversorFechas;
global using static Centrex.Funciones.generales_multiUsuario;
global using static Centrex.Funciones.ErrorLogger;

