Public Class proveedor
    Public id_proveedor As Integer
    Public taxNumber As String
    Public razon_social As String
    Public contacto As String
    Public telefono As String
    Public celular As String
    Public email As String
    Public id_pais_fiscal As Integer
    Public id_provincia_fiscal As Integer
    Public direccion_fiscal As String
    Public localidad_fiscal As String
    Public cp_fiscal As String
    Public id_pais_entrega As Integer
    Public id_provincia_entrega As Integer
    Public direccion_entrega As String
    Public localidad_entrega As String
    Public cp_entrega As String
    Public notas As String
    Public esInscripto As Boolean
    Public vendedor As String
    Public nombre As String
    Public direccion As String
    Public nombre_fantasia As String
    Public id As Integer
    Public activo As Boolean
    Public id_tipoDocumento As Integer
    Public id_claseFiscal As Integer
End Class
