// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Centrex.Models;

namespace Centrex.Models
{
    public partial class CentrexDbContext
    {

        [DbFunction("CalculoComprobante", "dbo")]
        public static string CalculoComprobante(string nombreAbreviado, int? puntoVenta, int? numeroComprobante)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("CantidadConLetra", "dbo")]
        public static string CantidadConLetra(decimal? Numero)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("idultimoingreso", "dbo")]
        public static int? idultimoingreso()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        public async Task<int?> idultimoingresoAsync()
            => await Database.SqlQueryRaw<int?>("select Value = [dbo].[idultimoingreso]()").SingleAsync();

        [DbFunction("idUltimoPresupuesto", "dbo")]
        public static int? idUltimoPresupuesto()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        public async Task<int?> idUltimoPresupuestoAsync()
            => await Database.SqlQueryRaw<int?>("select Value = [dbo].[idUltimoPresupuesto]()").SingleAsync();

        [DbFunction("mascaraCUIT", "dbo")]
        public static string mascaraCUIT(string cuit)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("milesArgentinos", "dbo")]
        public static string milesArgentinos(string valor)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
