// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Centrex.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Centrex.Models
{
    public partial class CentrexDbContext
    {
        private ICentrexDbContextProcedures? _procedures;

        public virtual ICentrexDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new CentrexDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ICentrexDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class CentrexDbContextProcedures : ICentrexDbContextProcedures
    {
        private readonly CentrexDbContext _context;

        public CentrexDbContextProcedures(CentrexDbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<datos_empresaResult>?> datos_empresaAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<datos_empresaResult>("EXEC @returnValue = [dbo].[datos_empresa]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<factura_cabeceraResult>?> factura_cabeceraAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idfc",
                    Value = idfc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<factura_cabeceraResult>("EXEC @returnValue = [dbo].[factura_cabecera] @idfc = @idfc", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<factura_detalleResult>?> factura_detalleAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idfc",
                    Value = idfc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<factura_detalleResult>("EXEC @returnValue = [dbo].[factura_detalle] @idfc = @idfc", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<presupuesto_cabeceraResult>?> presupuesto_cabeceraAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idfc",
                    Value = idfc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<presupuesto_cabeceraResult>("EXEC @returnValue = [dbo].[presupuesto_cabecera] @idfc = @idfc", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<produccion_cabeceraResult>?> produccion_cabeceraAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<produccion_cabeceraResult>("EXEC @returnValue = [dbo].[produccion_cabecera] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<produccion_detalleResult>?> produccion_detalleAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<produccion_detalleResult>("EXEC @returnValue = [dbo].[produccion_detalle] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<remito_cabeceraResult>?> remito_cabeceraAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idfc",
                    Value = idfc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<remito_cabeceraResult>("EXEC @returnValue = [dbo].[remito_cabecera] @idfc = @idfc", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<remito_detalleResult>?> remito_detalleAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idfc",
                    Value = idfc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<remito_detalleResult>("EXEC @returnValue = [dbo].[remito_detalle] @idfc = @idfc", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_cerrarComprobanteCompraAsync(int? id_comprobanteCompra, decimal? subtotal, decimal? impuestos, decimal? conceptos, decimal? total, string? nota, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_comprobanteCompra",
                    Value = id_comprobanteCompra ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "subtotal",
                    Precision = 18,
                    Scale = 3,
                    Value = subtotal ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "impuestos",
                    Precision = 18,
                    Scale = 3,
                    Value = impuestos ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "conceptos",
                    Precision = 18,
                    Scale = 3,
                    Value = conceptos ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "total",
                    Precision = 18,
                    Scale = 3,
                    Value = total ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "nota",
                    Size = -1,
                    Value = nota ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_cerrarComprobanteCompra] @id_comprobanteCompra = @id_comprobanteCompra, @subtotal = @subtotal, @impuestos = @impuestos, @conceptos = @conceptos, @total = @total, @nota = @nota", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_cierre_diarioAsync(int? id_empresa, string? fecha, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_empresa",
                    Value = id_empresa ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "fecha",
                    Size = 200,
                    Value = fecha ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_cierre_diario] @id_empresa = @id_empresa, @fecha = @fecha", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_cobro_cabeceraResult>?> SP_cobro_cabeceraAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_cobro_cabeceraResult>("EXEC @returnValue = [dbo].[SP_cobro_cabecera] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_comprobanteCompra_cabeceraResult>?> SP_comprobanteCompra_cabeceraAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_comprobanteCompra_cabeceraResult>("EXEC @returnValue = [dbo].[SP_comprobanteCompra_cabecera] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_comprobanteCompra_detalle_conceptosResult>?> SP_comprobanteCompra_detalle_conceptosAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_comprobanteCompra_detalle_conceptosResult>("EXEC @returnValue = [dbo].[SP_comprobanteCompra_detalle_conceptos] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_comprobanteCompra_detalle_impuestosResult>?> SP_comprobanteCompra_detalle_impuestosAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_comprobanteCompra_detalle_impuestosResult>("EXEC @returnValue = [dbo].[SP_comprobanteCompra_detalle_impuestos] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_comprobanteCompra_detalle_itemsResult>?> SP_comprobanteCompra_detalle_itemsAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_comprobanteCompra_detalle_itemsResult>("EXEC @returnValue = [dbo].[SP_comprobanteCompra_detalle_items] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_consulta_CC_ClienteResult>?> SP_consulta_CC_ClienteAsync(int? id_cliente, int? id_cc, string? fecha_desde, string? fecha_hasta, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_cliente",
                    Value = id_cliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_cc",
                    Value = id_cc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "fecha_desde",
                    Size = 200,
                    Value = fecha_desde ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "fecha_hasta",
                    Size = 200,
                    Value = fecha_hasta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_consulta_CC_ClienteResult>("EXEC @returnValue = [dbo].[SP_consulta_CC_Cliente] @id_cliente = @id_cliente, @id_cc = @id_cc, @fecha_desde = @fecha_desde, @fecha_hasta = @fecha_hasta", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_consulta_CC_ProveedorResult>?> SP_consulta_CC_ProveedorAsync(int? id_proveedor, int? id_cc, string? fecha_desde, string? fecha_hasta, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_proveedor",
                    Value = id_proveedor ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_cc",
                    Value = id_cc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "fecha_desde",
                    Size = 200,
                    Value = fecha_desde ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "fecha_hasta",
                    Size = 200,
                    Value = fecha_hasta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_consulta_CC_ProveedorResult>("EXEC @returnValue = [dbo].[SP_consulta_CC_Proveedor] @id_proveedor = @id_proveedor, @id_cc = @id_cc, @fecha_desde = @fecha_desde, @fecha_hasta = @fecha_hasta", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_detalle_cobros_chequesResult>?> SP_detalle_cobros_chequesAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_detalle_cobros_chequesResult>("EXEC @returnValue = [dbo].[SP_detalle_cobros_cheques] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_detalle_cobros_fc_importesResult>?> SP_detalle_cobros_fc_importesAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_detalle_cobros_fc_importesResult>("EXEC @returnValue = [dbo].[SP_detalle_cobros_fc_importes] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_detalle_cobros_retencionesResult>?> SP_detalle_cobros_retencionesAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_detalle_cobros_retencionesResult>("EXEC @returnValue = [dbo].[SP_detalle_cobros_retenciones] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_detalle_cobros_transferenciasResult>?> SP_detalle_cobros_transferenciasAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_detalle_cobros_transferenciasResult>("EXEC @returnValue = [dbo].[SP_detalle_cobros_transferencias] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_detalle_pagos_chequesResult>?> SP_detalle_pagos_chequesAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_detalle_pagos_chequesResult>("EXEC @returnValue = [dbo].[SP_detalle_pagos_cheques] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_detalle_pagos_fc_importesResult>?> SP_detalle_pagos_fc_importesAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_detalle_pagos_fc_importesResult>("EXEC @returnValue = [dbo].[SP_detalle_pagos_fc_importes] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_detalle_pagos_transferenciasResult>?> SP_detalle_pagos_transferenciasAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_detalle_pagos_transferenciasResult>("EXEC @returnValue = [dbo].[SP_detalle_pagos_transferencias] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_insertAsocItemsProduccionTMPAsync(int? id_tmpProduccion_asocItem, int? id_tmpProduccionItem, int? id_item, int? id_item_asoc, int? cantidad_item_asoc_enviada, int? id_usuario, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_tmpProduccion_asocItem",
                    Value = id_tmpProduccion_asocItem ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_tmpProduccionItem",
                    Value = id_tmpProduccionItem ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_item",
                    Value = id_item ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_item_asoc",
                    Value = id_item_asoc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "cantidad_item_asoc_enviada",
                    Value = cantidad_item_asoc_enviada ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_usuario",
                    Value = id_usuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_insertAsocItemsProduccionTMP] @id_tmpProduccion_asocItem = @id_tmpProduccion_asocItem, @id_tmpProduccionItem = @id_tmpProduccionItem, @id_item = @id_item, @id_item_asoc = @id_item_asoc, @cantidad_item_asoc_enviada = @cantidad_item_asoc_enviada, @id_usuario = @id_usuario, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_insertCobroAsync(int? id_cobro_oficial, int? id_cobro_no_oficial, string? fecha_cobro, int? id_cliente, int? id_cc, decimal? dineroEnCc, decimal? efectivo, decimal? totalTransferencia, decimal? totalCh, decimal? totalRetencion, decimal? total, bool? hayCheque, bool? hayTransferencia, bool? hayRetencion, int? id_anulaCobro, string? notas, string? firmante, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_cobro_oficial",
                    Value = id_cobro_oficial ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_cobro_no_oficial",
                    Value = id_cobro_no_oficial ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "fecha_cobro",
                    Size = 200,
                    Value = fecha_cobro ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "id_cliente",
                    Value = id_cliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_cc",
                    Value = id_cc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "dineroEnCc",
                    Precision = 18,
                    Scale = 3,
                    Value = dineroEnCc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "efectivo",
                    Precision = 18,
                    Scale = 3,
                    Value = efectivo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "totalTransferencia",
                    Precision = 18,
                    Scale = 3,
                    Value = totalTransferencia ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "totalCh",
                    Precision = 18,
                    Scale = 3,
                    Value = totalCh ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "totalRetencion",
                    Precision = 18,
                    Scale = 3,
                    Value = totalRetencion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "total",
                    Precision = 18,
                    Scale = 3,
                    Value = total ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "hayCheque",
                    Value = hayCheque ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "hayTransferencia",
                    Value = hayTransferencia ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "hayRetencion",
                    Value = hayRetencion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "id_anulaCobro",
                    Value = id_anulaCobro ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "notas",
                    Size = -1,
                    Value = notas ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "firmante",
                    Size = 100,
                    Value = firmante ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_insertCobro] @id_cobro_oficial = @id_cobro_oficial, @id_cobro_no_oficial = @id_cobro_no_oficial, @fecha_cobro = @fecha_cobro, @id_cliente = @id_cliente, @id_cc = @id_cc, @dineroEnCc = @dineroEnCc, @efectivo = @efectivo, @totalTransferencia = @totalTransferencia, @totalCh = @totalCh, @totalRetencion = @totalRetencion, @total = @total, @hayCheque = @hayCheque, @hayTransferencia = @hayTransferencia, @hayRetencion = @hayRetencion, @id_anulaCobro = @id_anulaCobro, @notas = @notas, @firmante = @firmante, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_insertComprobanteCompraAsync(string? fecha_comprobante, int? id_proveedor, decimal? id_cc, int? id_condicion_compra, int? id_tipoComprobante, decimal? id_moneda, decimal? tasaCambio, int? puntoVenta, int? numeroComprobante, string? cae, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "fecha_comprobante",
                    Size = 200,
                    Value = fecha_comprobante ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "id_proveedor",
                    Value = id_proveedor ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_cc",
                    Precision = 18,
                    Scale = 3,
                    Value = id_cc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "id_condicion_compra",
                    Value = id_condicion_compra ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_tipoComprobante",
                    Value = id_tipoComprobante ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_moneda",
                    Precision = 18,
                    Scale = 3,
                    Value = id_moneda ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "tasaCambio",
                    Precision = 18,
                    Scale = 3,
                    Value = tasaCambio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "puntoVenta",
                    Value = puntoVenta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "numeroComprobante",
                    Value = numeroComprobante ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "cae",
                    Size = 100,
                    Value = cae ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_insertComprobanteCompra] @fecha_comprobante = @fecha_comprobante, @id_proveedor = @id_proveedor, @id_cc = @id_cc, @id_condicion_compra = @id_condicion_compra, @id_tipoComprobante = @id_tipoComprobante, @id_moneda = @id_moneda, @tasaCambio = @tasaCambio, @puntoVenta = @puntoVenta, @numeroComprobante = @numeroComprobante, @cae = @cae, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_insertImpuestoAsync(string? nombre, decimal? porcentaje, bool? esRetencion, bool? esPercepcion, bool? activo, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "nombre",
                    Size = 200,
                    Value = nombre ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "porcentaje",
                    Precision = 18,
                    Scale = 4,
                    Value = porcentaje ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "esRetencion",
                    Value = esRetencion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "esPercepcion",
                    Value = esPercepcion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "activo",
                    Value = activo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_insertImpuesto] @nombre = @nombre, @porcentaje = @porcentaje, @esRetencion = @esRetencion, @esPercepcion = @esPercepcion, @activo = @activo, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_insertItemsOCTMPAsync(int? id_tmpOCItem, int? id_item, int? cantidad, decimal? precio, string? descript, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_tmpOCItem",
                    Value = id_tmpOCItem ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_item",
                    Value = id_item ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "cantidad",
                    Value = cantidad ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "precio",
                    Precision = 18,
                    Scale = 3,
                    Value = precio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "descript",
                    Size = 200,
                    Value = descript ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_insertItemsOCTMP] @id_tmpOCItem = @id_tmpOCItem, @id_item = @id_item, @cantidad = @cantidad, @precio = @precio, @descript = @descript, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_insertItemsProduccionTMPAsync(int? id_tmpProduccionItem, int? id_item, int? cantidad, string? descript, int? id_usuario, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_tmpProduccionItem",
                    Value = id_tmpProduccionItem ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_item",
                    Value = id_item ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "cantidad",
                    Value = cantidad ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "descript",
                    Size = 200,
                    Value = descript ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "id_usuario",
                    Value = id_usuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_insertItemsProduccionTMP] @id_tmpProduccionItem = @id_tmpProduccionItem, @id_item = @id_item, @cantidad = @cantidad, @descript = @descript, @id_usuario = @id_usuario, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_insertItemsTMPAsync(int? id_tmpPedidoItem, int? id_item, int? cantidad, decimal? precio, string? descript, string? item, int? id_usuario, string? id_unico, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_tmpPedidoItem",
                    Value = id_tmpPedidoItem ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_item",
                    Value = id_item ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "cantidad",
                    Value = cantidad ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "precio",
                    Precision = 18,
                    Scale = 2,
                    Value = precio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "descript",
                    Size = 200,
                    Value = descript ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "item",
                    Size = 100,
                    Value = item ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "id_usuario",
                    Value = id_usuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_unico",
                    Size = -1,
                    Value = id_unico ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_insertItemsTMP] @id_tmpPedidoItem = @id_tmpPedidoItem, @id_item = @id_item, @cantidad = @cantidad, @precio = @precio, @descript = @descript, @item = @item, @id_usuario = @id_usuario, @id_unico = @id_unico, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_insertPagoAsync(string? fecha_pago, int? id_proveedor, int? id_cc, decimal? dineroEnCc, decimal? efectivo, decimal? totalTransferencia, decimal? totalCh, decimal? total, bool? hayCheque, bool? hayTransferencia, bool? id_anulaPago, string? notas, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "fecha_pago",
                    Size = 200,
                    Value = fecha_pago ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "id_proveedor",
                    Value = id_proveedor ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_cc",
                    Value = id_cc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "dineroEnCc",
                    Precision = 18,
                    Scale = 3,
                    Value = dineroEnCc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "efectivo",
                    Precision = 18,
                    Scale = 3,
                    Value = efectivo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "totalTransferencia",
                    Precision = 18,
                    Scale = 3,
                    Value = totalTransferencia ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "totalCh",
                    Precision = 18,
                    Scale = 3,
                    Value = totalCh ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "total",
                    Precision = 18,
                    Scale = 3,
                    Value = total ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "hayCheque",
                    Value = hayCheque ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "hayTransferencia",
                    Value = hayTransferencia ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "id_anulaPago",
                    Value = id_anulaPago ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "notas",
                    Size = -1,
                    Value = notas ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_insertPago] @fecha_pago = @fecha_pago, @id_proveedor = @id_proveedor, @id_cc = @id_cc, @dineroEnCc = @dineroEnCc, @efectivo = @efectivo, @totalTransferencia = @totalTransferencia, @totalCh = @totalCh, @total = @total, @hayCheque = @hayCheque, @hayTransferencia = @hayTransferencia, @id_anulaPago = @id_anulaPago, @notas = @notas, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_insertTmpCobroRetencionAsync(int? id_impuesto, decimal? total, string? notas, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_impuesto",
                    Value = id_impuesto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "total",
                    Precision = 18,
                    Scale = 3,
                    Value = total ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "notas",
                    Size = -1,
                    Value = notas ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_insertTmpCobroRetencion] @id_impuesto = @id_impuesto, @total = @total, @notas = @notas, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_insertTmpTransferenciaAsync(int? id_cuentaBancaria, string? fecha, decimal? total, string? nComprobante, string? notas, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_cuentaBancaria",
                    Value = id_cuentaBancaria ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "fecha",
                    Size = 200,
                    Value = fecha ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "total",
                    Precision = 18,
                    Scale = 3,
                    Value = total ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "nComprobante",
                    Size = 200,
                    Value = nComprobante ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "notas",
                    Size = 200,
                    Value = notas ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_insertTmpTransferencia] @id_cuentaBancaria = @id_cuentaBancaria, @fecha = @fecha, @total = @total, @nComprobante = @nComprobante, @notas = @notas, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_pago_cabeceraResult>?> SP_pago_cabeceraAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id",
                    Value = id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_pago_cabeceraResult>("EXEC @returnValue = [dbo].[SP_pago_cabecera] @id = @id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_proforma_cabeceraResult>?> SP_proforma_cabeceraAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idfc",
                    Value = idfc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_proforma_cabeceraResult>("EXEC @returnValue = [dbo].[SP_proforma_cabecera] @idfc = @idfc", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_proforma_detalleResult>?> SP_proforma_detalleAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idfc",
                    Value = idfc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_proforma_detalleResult>("EXEC @returnValue = [dbo].[SP_proforma_detalle] @idfc = @idfc", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_updateAsocItemsProduccionTMPAsync(int? id_tmpProduccion_asocItem, int? id_tmpProduccionItem, int? id_item, int? id_item_asoc, int? cantidad_item_asoc_enviada, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_tmpProduccion_asocItem",
                    Value = id_tmpProduccion_asocItem ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_tmpProduccionItem",
                    Value = id_tmpProduccionItem ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_item",
                    Value = id_item ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_item_asoc",
                    Value = id_item_asoc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "cantidad_item_asoc_enviada",
                    Value = cantidad_item_asoc_enviada ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_updateAsocItemsProduccionTMP] @id_tmpProduccion_asocItem = @id_tmpProduccion_asocItem, @id_tmpProduccionItem = @id_tmpProduccionItem, @id_item = @id_item, @id_item_asoc = @id_item_asoc, @cantidad_item_asoc_enviada = @cantidad_item_asoc_enviada, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_updateComprobanteCompraAsync(int? id_comprobanteCompra, string? fecha_comprobante, int? id_proveedor, decimal? id_cc, int? id_condicion_compra, int? id_tipoComprobante, decimal? id_moneda, decimal? tasaCambio, int? puntoVenta, int? numeroComprobante, string? cae, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_comprobanteCompra",
                    Value = id_comprobanteCompra ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "fecha_comprobante",
                    Size = 200,
                    Value = fecha_comprobante ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "id_proveedor",
                    Value = id_proveedor ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_cc",
                    Precision = 18,
                    Scale = 3,
                    Value = id_cc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "id_condicion_compra",
                    Value = id_condicion_compra ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_tipoComprobante",
                    Value = id_tipoComprobante ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_moneda",
                    Precision = 18,
                    Scale = 3,
                    Value = id_moneda ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "tasaCambio",
                    Precision = 18,
                    Scale = 3,
                    Value = tasaCambio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "puntoVenta",
                    Value = puntoVenta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "numeroComprobante",
                    Value = numeroComprobante ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "cae",
                    Size = 100,
                    Value = cae ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_updateComprobanteCompra] @id_comprobanteCompra = @id_comprobanteCompra, @fecha_comprobante = @fecha_comprobante, @id_proveedor = @id_proveedor, @id_cc = @id_cc, @id_condicion_compra = @id_condicion_compra, @id_tipoComprobante = @id_tipoComprobante, @id_moneda = @id_moneda, @tasaCambio = @tasaCambio, @puntoVenta = @puntoVenta, @numeroComprobante = @numeroComprobante, @cae = @cae", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_updateItemsOCTMPAsync(int? id_tmpOCItem, int? id_item, int? cantidad, decimal? precio, string? descript, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_tmpOCItem",
                    Value = id_tmpOCItem ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_item",
                    Value = id_item ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "cantidad",
                    Value = cantidad ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "precio",
                    Precision = 18,
                    Scale = 3,
                    Value = precio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "descript",
                    Size = 200,
                    Value = descript ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_updateItemsOCTMP] @id_tmpOCItem = @id_tmpOCItem, @id_item = @id_item, @cantidad = @cantidad, @precio = @precio, @descript = @descript, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_updateItemsProduccionTMPAsync(int? id_tmpProduccionItem, int? id_item, int? cantidad, string? descript, int? id_usuario, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_tmpProduccionItem",
                    Value = id_tmpProduccionItem ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_item",
                    Value = id_item ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "cantidad",
                    Value = cantidad ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "descript",
                    Size = 200,
                    Value = descript ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "id_usuario",
                    Value = id_usuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_updateItemsProduccionTMP] @id_tmpProduccionItem = @id_tmpProduccionItem, @id_item = @id_item, @cantidad = @cantidad, @descript = @descript, @id_usuario = @id_usuario, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_updateItemsTMPAsync(int? id_tmpPedidoItem, int? id_item, int? cantidad, decimal? precio, string? descript, string? item, int? id_usuario, string? id_unico, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterresultado = new SqlParameter
            {
                ParameterName = "resultado",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = resultado?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_tmpPedidoItem",
                    Value = id_tmpPedidoItem ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_item",
                    Value = id_item ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "cantidad",
                    Value = cantidad ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "precio",
                    Precision = 18,
                    Scale = 2,
                    Value = precio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "descript",
                    Size = 200,
                    Value = descript ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "item",
                    Size = 100,
                    Value = item ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "id_usuario",
                    Value = id_usuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_unico",
                    Size = -1,
                    Value = id_unico ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterresultado,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_updateItemsTMP] @id_tmpPedidoItem = @id_tmpPedidoItem, @id_item = @id_item, @cantidad = @cantidad, @precio = @precio, @descript = @descript, @item = @item, @id_usuario = @id_usuario, @id_unico = @id_unico, @resultado = @resultado OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            resultado?.SetValue(parameterresultado.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
