// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class datos_empresaResult
    {
        [StringLength(100)]
        public string nombre { get; set; } = default!;
        [StringLength(2147483647)]
        public string direccion { get; set; } = default!;
        [StringLength(50)]
        public string? cuit { get; set; }
        [StringLength(50)]
        public string? ingresos_brutos { get; set; }
        [StringLength(10)]
        public string? inicio_actividades { get; set; }
        public byte[]? logo { get; set; }
    }
}
