// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Centrex.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Centrex.Models
{
    public partial interface ICentrexDbContextProcedures
    {
        Task<List<datos_empresaResult>?> datos_empresaAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<factura_cabeceraResult>?> factura_cabeceraAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<factura_detalleResult>?> factura_detalleAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<presupuesto_cabeceraResult>?> presupuesto_cabeceraAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<produccion_cabeceraResult>?> produccion_cabeceraAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<produccion_detalleResult>?> produccion_detalleAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<remito_cabeceraResult>?> remito_cabeceraAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<remito_detalleResult>?> remito_detalleAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_cerrarComprobanteCompraAsync(int? id_comprobanteCompra, decimal? subtotal, decimal? impuestos, decimal? conceptos, decimal? total, string? nota, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_cierre_diarioAsync(int? id_empresa, string? fecha, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_cobro_cabeceraResult>?> SP_cobro_cabeceraAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_comprobanteCompra_cabeceraResult>?> SP_comprobanteCompra_cabeceraAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_comprobanteCompra_detalle_conceptosResult>?> SP_comprobanteCompra_detalle_conceptosAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_comprobanteCompra_detalle_impuestosResult>?> SP_comprobanteCompra_detalle_impuestosAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_comprobanteCompra_detalle_itemsResult>?> SP_comprobanteCompra_detalle_itemsAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_consulta_CC_ClienteResult>?> SP_consulta_CC_ClienteAsync(int? id_cliente, int? id_cc, string? fecha_desde, string? fecha_hasta, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_consulta_CC_ProveedorResult>?> SP_consulta_CC_ProveedorAsync(int? id_proveedor, int? id_cc, string? fecha_desde, string? fecha_hasta, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_detalle_cobros_chequesResult>?> SP_detalle_cobros_chequesAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_detalle_cobros_fc_importesResult>?> SP_detalle_cobros_fc_importesAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_detalle_cobros_retencionesResult>?> SP_detalle_cobros_retencionesAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_detalle_cobros_transferenciasResult>?> SP_detalle_cobros_transferenciasAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_detalle_pagos_chequesResult>?> SP_detalle_pagos_chequesAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_detalle_pagos_fc_importesResult>?> SP_detalle_pagos_fc_importesAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_detalle_pagos_transferenciasResult>?> SP_detalle_pagos_transferenciasAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_insertAsocItemsProduccionTMPAsync(int? id_tmpProduccion_asocItem, int? id_tmpProduccionItem, int? id_item, int? id_item_asoc, int? cantidad_item_asoc_enviada, int? id_usuario, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_insertCobroAsync(int? id_cobro_oficial, int? id_cobro_no_oficial, string? fecha_cobro, int? id_cliente, int? id_cc, decimal? dineroEnCc, decimal? efectivo, decimal? totalTransferencia, decimal? totalCh, decimal? totalRetencion, decimal? total, bool? hayCheque, bool? hayTransferencia, bool? hayRetencion, int? id_anulaCobro, string? notas, string? firmante, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_insertComprobanteCompraAsync(string? fecha_comprobante, int? id_proveedor, decimal? id_cc, int? id_condicion_compra, int? id_tipoComprobante, decimal? id_moneda, decimal? tasaCambio, int? puntoVenta, int? numeroComprobante, string? cae, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_insertImpuestoAsync(string? nombre, decimal? porcentaje, bool? esRetencion, bool? esPercepcion, bool? activo, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_insertItemsOCTMPAsync(int? id_tmpOCItem, int? id_item, int? cantidad, decimal? precio, string? descript, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_insertItemsProduccionTMPAsync(int? id_tmpProduccionItem, int? id_item, int? cantidad, string? descript, int? id_usuario, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_insertItemsTMPAsync(int? id_tmpPedidoItem, int? id_item, int? cantidad, decimal? precio, string? descript, string? item, int? id_usuario, string? id_unico, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_insertPagoAsync(string? fecha_pago, int? id_proveedor, int? id_cc, decimal? dineroEnCc, decimal? efectivo, decimal? totalTransferencia, decimal? totalCh, decimal? total, bool? hayCheque, bool? hayTransferencia, bool? id_anulaPago, string? notas, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_insertTmpCobroRetencionAsync(int? id_impuesto, decimal? total, string? notas, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_insertTmpTransferenciaAsync(int? id_cuentaBancaria, string? fecha, decimal? total, string? nComprobante, string? notas, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_pago_cabeceraResult>?> SP_pago_cabeceraAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_proforma_cabeceraResult>?> SP_proforma_cabeceraAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_proforma_detalleResult>?> SP_proforma_detalleAsync(int? idfc, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_updateAsocItemsProduccionTMPAsync(int? id_tmpProduccion_asocItem, int? id_tmpProduccionItem, int? id_item, int? id_item_asoc, int? cantidad_item_asoc_enviada, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_updateComprobanteCompraAsync(int? id_comprobanteCompra, string? fecha_comprobante, int? id_proveedor, decimal? id_cc, int? id_condicion_compra, int? id_tipoComprobante, decimal? id_moneda, decimal? tasaCambio, int? puntoVenta, int? numeroComprobante, string? cae, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_updateItemsOCTMPAsync(int? id_tmpOCItem, int? id_item, int? cantidad, decimal? precio, string? descript, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_updateItemsProduccionTMPAsync(int? id_tmpProduccionItem, int? id_item, int? cantidad, string? descript, int? id_usuario, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> SP_updateItemsTMPAsync(int? id_tmpPedidoItem, int? id_item, int? cantidad, decimal? precio, string? descript, string? item, int? id_usuario, string? id_unico, OutputParameter<int?> resultado, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
