// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class presupuesto_cabeceraResult
    {
        [StringLength(10)]
        public string? order_date { get; set; }
        [StringLength(100)]
        public string cust_name { get; set; } = default!;
        [StringLength(50)]
        public string? cust_taxNumber { get; set; }
        [StringLength(200)]
        public string? cust_address { get; set; }
        [StringLength(21)]
        public string? inscripto { get; set; }
        [StringLength(100)]
        public string provincia { get; set; } = default!;
        [StringLength(200)]
        public string? localidad { get; set; }
        [StringLength(51)]
        public string subtotal { get; set; } = default!;
        [StringLength(51)]
        public string iva { get; set; } = default!;
        [StringLength(51)]
        public string total { get; set; } = default!;
        [StringLength(200)]
        public string? nota1 { get; set; }
        [StringLength(200)]
        public string? nota2 { get; set; }
        public int? idpresupuesto { get; set; }
    }
}
