// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class produccion_detalleResult
    {
        public int id { get; set; }
        public int id_produccion { get; set; }
        [StringLength(50)]
        public string item { get; set; } = default!;
        [StringLength(100)]
        public string? descript { get; set; }
        public int cantidad { get; set; }
        public int cantidad_recibida { get; set; }
        [StringLength(2)]
        public string activo { get; set; } = default!;
    }
}
