// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class produccion_cabeceraResult
    {
        public int id { get; set; }
        [StringLength(100)]
        public string proveedor { get; set; } = default!;
        [StringLength(200)]
        public string? direccion_fiscal { get; set; }
        [StringLength(200)]
        public string? localidad_fiscal { get; set; }
        [StringLength(100)]
        public string provincia_fiscal { get; set; } = default!;
        [StringLength(50)]
        public string? taxNumber { get; set; }
        [StringLength(20)]
        public string? fecha_carga { get; set; }
        [StringLength(20)]
        public string? fecha_envio { get; set; }
        [StringLength(20)]
        public string? fecha_recepcion { get; set; }
        [StringLength(2)]
        public string enviado { get; set; } = default!;
        [StringLength(2)]
        public string recibido { get; set; } = default!;
        [StringLength(2147483647)]
        public string? notas { get; set; }
        [StringLength(2)]
        public string activo { get; set; } = default!;
    }
}
