// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class remito_detalleResult
    {
        [StringLength(50)]
        public string? item_code { get; set; }
        [StringLength(100)]
        public string? item_desc { get; set; }
        [StringLength(50)]
        public string? item_qty { get; set; }
    }
}
