// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class remito_cabeceraResult
    {
        [StringLength(20)]
        public string? order_date { get; set; }
        [StringLength(100)]
        public string cust_name { get; set; } = default!;
        [StringLength(50)]
        public string? cust_taxNumber { get; set; }
        [StringLength(200)]
        public string? cust_address { get; set; }
        [StringLength(21)]
        public string? inscripto { get; set; }
        [StringLength(100)]
        public string provincia { get; set; } = default!;
        [StringLength(200)]
        public string? localidad { get; set; }
        [Column("subtotal", TypeName = "decimal(18,3)")]
        public decimal subtotal { get; set; }
        [Column("iva", TypeName = "decimal(18,3)")]
        public decimal? iva { get; set; }
        [StringLength(51)]
        public string total { get; set; } = default!;
        [StringLength(200)]
        public string? nota1 { get; set; }
        [StringLength(200)]
        public string? nota2 { get; set; }
    }
}
