// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class SP_consulta_CC_ProveedorResult
    {
        public int ID { get; set; }
        public DateOnly Fecha { get; set; }
        [StringLength(50)]
        public string? Comprobante { get; set; }
        [Column("Débito", TypeName = "decimal(18,3)")]
        public decimal? Débito { get; set; }
        [Column("Crédito", TypeName = "decimal(20,3)")]
        public decimal? Crédito { get; set; }
        [Column("Saldo", TypeName = "decimal(38,3)")]
        public decimal? Saldo { get; set; }
    }
}
