// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class SP_comprobanteCompra_detalle_impuestosResult
    {
        public int id { get; set; }
        [StringLength(100)]
        public string impuesto { get; set; } = default!;
        [Column("importe", TypeName = "decimal(18,3)")]
        public decimal importe { get; set; }
    }
}
