// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class SP_comprobanteCompra_detalle_itemsResult
    {
        public int id { get; set; }
        [StringLength(50)]
        public string codigo { get; set; } = default!;
        [StringLength(54)]
        public string? descript { get; set; }
        public int cantidad { get; set; }
        [Column("precio", TypeName = "decimal(18,2)")]
        public decimal precio { get; set; }
    }
}
