// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class SP_comprobanteCompra_cabeceraResult
    {
        [StringLength(20)]
        public string? fecha_carga { get; set; }
        [StringLength(20)]
        public string? fecha_comprobante { get; set; }
        [StringLength(4000)]
        public string comprobante { get; set; } = default!;
        [StringLength(100)]
        public string condicion_compra { get; set; } = default!;
        [StringLength(100)]
        public string razon_social { get; set; } = default!;
        [StringLength(50)]
        public string? supp_taxNumber { get; set; }
        [StringLength(200)]
        public string? supp_address { get; set; }
        [StringLength(21)]
        public string? inscripto { get; set; }
        [StringLength(100)]
        public string provincia { get; set; } = default!;
        [StringLength(200)]
        public string? localidad { get; set; }
        [StringLength(51)]
        public string subtotal { get; set; } = default!;
        [StringLength(51)]
        public string impuestos { get; set; } = default!;
        [StringLength(51)]
        public string conceptos { get; set; } = default!;
        [StringLength(51)]
        public string total { get; set; } = default!;
        [StringLength(51)]
        public string tasa_cambio { get; set; } = default!;
        [StringLength(2147483647)]
        public string? nota { get; set; }
        [StringLength(50)]
        public string? cae { get; set; }
    }
}
