// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class SP_comprobanteCompra_detalle_conceptosResult
    {
        public int id { get; set; }
        [StringLength(100)]
        public string concepto { get; set; } = default!;
        [Column("subtotal", TypeName = "decimal(18,3)")]
        public decimal subtotal { get; set; }
        [Column("iva", TypeName = "decimal(18,3)")]
        public decimal iva { get; set; }
        [Column("total", TypeName = "decimal(18,3)")]
        public decimal total { get; set; }
    }
}
