// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class SP_cobro_cabeceraResult
    {
        [StringLength(50)]
        public string? id_cobro { get; set; }
        [StringLength(20)]
        public string? fecha_carga { get; set; }
        [StringLength(20)]
        public string? fecha_cobro { get; set; }
        public int id_cliente { get; set; }
        [StringLength(100)]
        public string razon_social { get; set; } = default!;
        [StringLength(51)]
        public string dineroEnCc { get; set; } = default!;
        [StringLength(51)]
        public string efectivo { get; set; } = default!;
        [StringLength(51)]
        public string totalTransferencia { get; set; } = default!;
        [StringLength(51)]
        public string totalCh { get; set; } = default!;
        [StringLength(51)]
        public string totalRetencion { get; set; } = default!;
        [StringLength(51)]
        public string total { get; set; } = default!;
        public bool hayCheque { get; set; }
        public bool hayTransferencia { get; set; }
        public bool hayRetencion { get; set; }
        public bool activo { get; set; }
        public int? id_anulaCobro { get; set; }
        [StringLength(2147483647)]
        public string? notas { get; set; }
        [StringLength(50)]
        public string firmante { get; set; } = default!;
        [StringLength(180)]
        public string? totalChar { get; set; }
        [StringLength(200)]
        public string? direccion_fiscal { get; set; }
        [StringLength(50)]
        public string? taxNumber { get; set; }
        [StringLength(21)]
        public string? inscripto { get; set; }
    }
}
