// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class SP_detalle_cobros_retencionesResult
    {
        public int id_retencion { get; set; }
        [StringLength(100)]
        public string retencion { get; set; } = default!;
        [StringLength(51)]
        public string total { get; set; } = default!;
        [StringLength(2147483647)]
        public string? notas { get; set; }
    }
}
