// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class SP_detalle_pagos_transferenciasResult
    {
        public int id_transferencia { get; set; }
        [StringLength(20)]
        public string? fecha { get; set; }
        [StringLength(100)]
        public string banco { get; set; } = default!;
        [StringLength(100)]
        public string cuenta_bancaria { get; set; } = default!;
        [StringLength(51)]
        public string total { get; set; } = default!;
        [StringLength(50)]
        public string? nComprobante { get; set; }
        [StringLength(2147483647)]
        public string? notas { get; set; }
    }
}
