// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class SP_detalle_cobros_fc_importesResult
    {
        public int id_cobro { get; set; }
        [StringLength(20)]
        public string? fecha { get; set; }
        [StringLength(50)]
        public string nfactura { get; set; } = default!;
        [StringLength(51)]
        public string importe { get; set; } = default!;
    }
}
