// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Centrex.Models
{
    public partial class SP_detalle_cobros_chequesResult
    {
        public int id_cheque { get; set; }
        [StringLength(20)]
        public string? fecha_ingreso { get; set; }
        [StringLength(100)]
        public string banco { get; set; } = default!;
        public int nCheque { get; set; }
        [StringLength(51)]
        public string importe { get; set; } = default!;
    }
}
